kind: Service
apiVersion: v1
metadata:
  name: argus-agent-service
  namespace: argus-agent-prod
spec:
  selector:
    app: argus-agent
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
