apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-argus.fullname" . }}-agent
  namespace: {{ .Values.argus.namespace }}
  labels:
    {{- include "helm-argus.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  type: {{ .Values.argus.service.type }}
  ports:
    - port: {{ .Values.argus.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm-argus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: agent