"""
Summary Slack Client

Provides Slack integration for posting incident summaries.
Uses Block Kit for rich formatting.
"""

import logging
from typing import Dict, List, Any, Optional

from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError

logger = logging.getLogger(__name__)


class SummarySlackClient:
    """
    Slack client for posting incident summaries.

    This client:
    - Posts formatted summary messages to Slack
    - Uses Block Kit for rich visual formatting
    - Supports threading to keep summaries with the incident discussion
    """

    def __init__(self, token: str, default_channel: str = "#incidents"):
        """
        Initialize Slack client.

        Args:
            token: Slack Bot OAuth token (xoxb-...)
            default_channel: Default channel for summary messages
        """
        self.client = WebClient(token=token)
        self.default_channel = default_channel

    def format_summary_blocks(
        self,
        incident_id: str,
        summary: str,
        all_succeeded: bool,
        resolution_time_seconds: float,
    ) -> List[Dict[str, Any]]:
        """
        Format incident summary as Slack Block Kit blocks.

        Args:
            incident_id: Unique incident identifier
            summary: Full summary text
            all_succeeded: Whether all actions succeeded
            resolution_time_seconds: Time from incident to resolution

        Returns:
            List of Slack Block Kit blocks
        """
        # Status indicators
        status_emoji = ":white_check_mark:" if all_succeeded else ":warning:"
        status_text = "RESOLVED" if all_succeeded else "PARTIALLY RESOLVED"
        status_color = "good" if all_succeeded else "warning"

        # Format duration
        duration = self._format_duration(resolution_time_seconds)

        blocks = [
            # Header
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"{status_emoji} Incident {status_text}",
                    "emoji": True
                }
            },
            # Incident ID and Duration
            {
                "type": "section",
                "fields": [
                    {
                        "type": "mrkdwn",
                        "text": f"*Incident ID:*\n`{incident_id}`"
                    },
                    {
                        "type": "mrkdwn",
                        "text": f"*Resolution Time:*\n{duration}"
                    }
                ]
            },
            {"type": "divider"},
            # Summary content (split into sections if too long)
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": self._truncate_for_slack(summary, 2900)
                }
            },
            {"type": "divider"},
            # Footer with timestamp
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": f":robot_face: Generated by DevOps Agent | <!date^{int(__import__('time').time())}^{{date_short}} {{time}}|now>"
                    }
                ]
            }
        ]

        return blocks

    async def post_summary(
        self,
        incident_id: str,
        summary: str,
        all_succeeded: bool,
        resolution_time_seconds: float,
        channel: Optional[str] = None,
        thread_ts: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Post incident summary to Slack.

        Args:
            incident_id: Unique incident identifier
            summary: Full summary text
            all_succeeded: Whether all actions succeeded
            resolution_time_seconds: Time from incident to resolution
            channel: Slack channel (defaults to self.default_channel)
            thread_ts: Thread timestamp to reply to (optional)

        Returns:
            Dict with 'ok', 'ts' (message timestamp), and 'channel'
        """
        channel = channel or self.default_channel

        blocks = self.format_summary_blocks(
            incident_id=incident_id,
            summary=summary,
            all_succeeded=all_succeeded,
            resolution_time_seconds=resolution_time_seconds,
        )

        # Fallback text for notifications
        status = "RESOLVED" if all_succeeded else "PARTIALLY RESOLVED"
        fallback_text = f"Incident {incident_id} {status}"

        try:
            response = self.client.chat_postMessage(
                channel=channel,
                blocks=blocks,
                text=fallback_text,
                thread_ts=thread_ts,
            )

            logger.info(
                f"[Summary Slack] Summary posted for {incident_id} "
                f"to {channel}, ts={response['ts']}"
            )

            return {
                "ok": True,
                "ts": response["ts"],
                "channel": response["channel"],
            }

        except SlackApiError as e:
            logger.error(f"[Summary Slack] Error posting summary: {e.response['error']}")
            return {
                "ok": False,
                "error": str(e.response["error"]),
            }

    async def post_postmortem_link(
        self,
        incident_id: str,
        ticket_id: str,
        ticket_url: Optional[str] = None,
        channel: Optional[str] = None,
        thread_ts: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Post postmortem ticket link to Slack thread.

        Args:
            incident_id: Unique incident identifier
            ticket_id: Postmortem ticket ID (e.g., "POST-123")
            ticket_url: URL to the ticket (optional)
            channel: Slack channel
            thread_ts: Thread to reply to

        Returns:
            Dict with result info
        """
        channel = channel or self.default_channel

        # Build message
        if ticket_url:
            text = f":memo: Postmortem ticket created: <{ticket_url}|{ticket_id}>"
        else:
            text = f":memo: Postmortem ticket created: `{ticket_id}`"

        blocks = [
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": text
                }
            },
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": f"Please complete the postmortem within 48 hours for incident `{incident_id}`"
                    }
                ]
            }
        ]

        try:
            response = self.client.chat_postMessage(
                channel=channel,
                blocks=blocks,
                text=f"Postmortem ticket {ticket_id} created",
                thread_ts=thread_ts,
            )

            return {
                "ok": True,
                "ts": response["ts"],
                "channel": response["channel"],
            }

        except SlackApiError as e:
            logger.error(f"[Summary Slack] Error posting postmortem link: {e.response['error']}")
            return {
                "ok": False,
                "error": str(e.response["error"]),
            }

    def _format_duration(self, seconds: float) -> str:
        """Format duration in seconds to human-readable string."""
        if seconds < 60:
            return f"{int(seconds)} seconds"
        elif seconds < 3600:
            minutes = int(seconds / 60)
            return f"{minutes} minute{'s' if minutes != 1 else ''}"
        else:
            hours = int(seconds / 3600)
            minutes = int((seconds % 3600) / 60)
            parts = [f"{hours} hour{'s' if hours != 1 else ''}"]
            if minutes > 0:
                parts.append(f"{minutes} min")
            return " ".join(parts)

    def _truncate_for_slack(self, text: str, max_length: int = 2900) -> str:
        """
        Truncate text to fit Slack's block text limit.

        Slack Block Kit has a 3000 character limit per text block.
        We use 2900 to leave room for formatting.

        Args:
            text: Text to truncate
            max_length: Maximum length

        Returns:
            Truncated text with ellipsis if needed
        """
        if len(text) <= max_length:
            return text

        return text[:max_length - 3] + "..."
