kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argus-junior-role-binding
  namespace: argus-agent-dev
subjects:
  - kind: ServiceAccount
    name: dev-sa
    namespace: argus-agent-dev
roleRef:
  kind: Role
  name: argus-junior-role
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argus-senior-role-binding
subjects:
  - kind: ServiceAccount
    name: prod-sa
    namespace: argus-agent-prod
roleRef:
  kind: ClusterRole
  name: argus-senior-cluster-role
  apiGroup: rbac.authorization.k8s.io
